default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  GIT_DEPTH: 0
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

stages:
  - launchability
  - updateLocalization

launch-ability:
  only:
    - pushes
  stage: launchability
  script:
    - ./build.sh EnsureLaunchability
    - ./build.sh EnsureLaunchability --TargetFactorioVersion latest

pull-localization:
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "trigger"
      when: always
    - when: never
  stage: updateLocalization
  script:
    - git fetch
    - git checkout $CI_COMMIT_BRANCH
    - git pull
    - ./build.sh  PullLocalization
    - git config --global user.email 'skproch@yandex.ru'
    - git add . && git diff --quiet && git diff --staged --quiet || (git commit -am 'Updated ParanoidalLocale mod' --author='SKProCHs Bot <skproch@yandex.ru>' && git push https://paranoidal:$GITLAB_ACCESS_TOKEN@gitlab.com/paranoidal/modpack.git master)