default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  GIT_DEPTH: 0
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

stages:
  - launchability

launch-ability:
  stage: launchability
  script:
    - ./build.sh EnsureLaunchability